[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
poidh = "HFD3185JaPEQRXAcCgiwJT6amphebDJJRsCQtwCQyovZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
